import { Image } from "react-grid-gallery";

export interface CustomImage extends Image {
  original: string;
}

export const images: CustomImage[] = [
  {
    src: "/photos/1.jpg",
    original: "/photos/1.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/2.jpg",
    original: "/photos/2.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/3.jpg",
    original: "/photos/3.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/4.jpg",
    original: "/photos/4.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/5.jpg",
    original: "/photos/5.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/6.jpg",
    original: "/photos/6.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/7.jpg",
    original: "/photos/7.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/8.jpg",
    original: "/photos/8.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/9.jpg",
    original: "/photos/9.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/10.jpg",
    original: "/photos/10.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/11.jpg",
    original: "/photos/11.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/12.jpg",
    original: "/photos/12.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/13.jpg",
    original: "/photos/13.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/14.jpg",
    original: "/photos/14.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/15.jpg",
    original: "/photos/15.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/16.jpg",
    original: "/photos/16.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/17.jpg",
    original: "/photos/17.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/18.jpg",
    original: "/photos/18.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/19.jpg",
    original: "/photos/19.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/20.jpg",
    original: "/photos/20.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/21.jpg",
    original: "/photos/21.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/22.jpg",
    original: "/photos/22.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/23.jpg",
    original: "/photos/23.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/24.jpg",
    original: "/photos/24.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/25.jpg",
    original: "/photos/25.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/26.jpg",
    original: "/photos/26.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/27.jpg",
    original: "/photos/27.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/28.jpg",
    original: "/photos/28.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/29.jpg",
    original: "/photos/29.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/30.jpg",
    original: "/photos/30.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/31.jpg",
    original: "/photos/31.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/32.jpg",
    original: "/photos/32.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/33.jpg",
    original: "/photos/33.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/34.jpg",
    original: "/photos/34.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/35.jpg",
    original: "/photos/35.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/36.jpg",
    original: "/photos/36.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/37.jpg",
    original: "/photos/37.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/38.jpg",
    original: "/photos/38.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/39.jpg",
    original: "/photos/39.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/40.jpg",
    original: "/photos/40.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/41.jpg",
    original: "/photos/41.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/42.jpg",
    original: "/photos/42.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/43.jpg",
    original: "/photos/43.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/44.jpg",
    original: "/photos/44.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/45.jpg",
    original: "/photos/45.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/46.jpg",
    original: "/photos/46.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/47.jpg",
    original: "/photos/47.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/48.jpg",
    original: "/photos/48.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/49.jpg",
    original: "/photos/49.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/50.jpg",
    original: "/photos/50.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/51.jpg",
    original: "/photos/51.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/52.jpg",
    original: "/photos/52.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/53.jpg",
    original: "/photos/53.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/54.jpg",
    original: "/photos/54.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/55.jpg",
    original: "/photos/55.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/56.jpg",
    original: "/photos/56.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/57.jpg",
    original: "/photos/57.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/58.jpg",
    original: "/photos/58.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/59.jpg",
    original: "/photos/59.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/60.jpg",
    original: "/photos/60.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/61.jpg",
    original: "/photos/61.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/62.jpg",
    original: "/photos/62.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/63.jpg",
    original: "/photos/63.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/64.jpg",
    original: "/photos/64.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/65.jpg",
    original: "/photos/65.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/66.jpg",
    original: "/photos/66.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/67.jpg",
    original: "/photos/67.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/68.jpg",
    original: "/photos/68.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/69.jpg",
    original: "/photos/69.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/70.jpg",
    original: "/photos/70.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/71.jpg",
    original: "/photos/71.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/72.jpg",
    original: "/photos/72.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/73.jpg",
    original: "/photos/73.jpg",
    width: 240,
    height: 320,
  },
  {
    src: "/photos/74.jpg",
    original: "/photos/74.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
  {
    src: "/photos/75.jpg",
    original: "/photos/75.jpg",
    width: 320,
    height: 212,
    caption: "",
  },
];
